sudo: true
os: trusty
cache: false
env:
  matrix:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
  global:
    secure: GaS++TJckSRf1thdy524pDwSgxQ+SWFs7v63g2wGv0dgJmFZV2clscyQO1a+OWCh4b9/y2KGnr+8XZ7aEF8JjZ97wnhFuplQl9mEt01YSyCHCysrM0n3A3/Ih8tuiiDvS14hKdR3WEcrb45Qh43jYSULyy1eXJWVvH8h0C8CHn7W370I0EMMdKc+5mk/ixGIScqarmHce/qGjk3TPOvU0VsbroDTNQSoj7IrqHjpRp5XttLBsaHQ0XtpFrA702WBWjqX+pskXyrJZeSsAzM0RIy/n5cnO/xMbksBK+E0AHSLqn3mUXXJCg2JfFLia/w0lwfWZiGgT9RPI3gEfqAaRSQR/aqWiMJ//UCHVVtRdcr1eZbWGyqrZPZx1el7q1z3YCEWyKvazmaYNUZTqnVq6Od8BYV7Ls446n/aBDQF4EBq19ro4gcn92Tw98x1oFoN0a8T7dRQ75SyEvsWXtmhf/bNAG6O5P52dwogdkUL21avalp1BfyE0uFEYZOohglq8WVvigTugymK0+pe6JfKX4nDSePSUPI0oFORnwnfag+hicBaS3VNSKhaWeeG+cqXWiDMoQHJZrSaqGmdDLNhhaJdMbX1l0XhsdMlt44LJaMbuRY4cIschhqoORiHL7Gkb69XT0FMESK85uwroeThExmc0fMOXN83ckAM6EmBGn8=
before_install:
- openssl aes-256-cbc -k "$super_secret_password" -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --username $USERNAME --jwtkeyfile assets/server.key --setdefaultdevhubusername -a HubOrg
script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg --wait
  2
- sfdx force:org:display -u ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg --wait 10
- sfdx force:org:delete -u ciorg -p
